### ISSUE TITLE
Aba de subsídios possui menos colunas de dados que o especificado no modelo

### ISSUE THREAD

**Issue by viniagostini** [dadosjusbr/parser#19]
Em alguns casos a aba de subsídios possui menos colunas de dados que o especificado no [modelo de planilhas](http://www.cnj.jus.br/files/conteudo/arquivo/2017/11/becada0200f03cb5a129ce57513f8ff3.xls),

Isso faz com que os campos não estejam na posição esperada pelo parser, atribuindo assim valores errados para os campos.

É necessário pensar em uma estratégia para reconhecer o caso geral e esse caso específico, selecionando assim o modelo adequado para que esses dados sejam coletados.

As planilhas com esse problema são:

| Tribunal                    | Mês/ano referência | arquivo                              |
|-----------------------------|--------------------|--------------------------------------|
| Tribunal Justiça de Sergipe | 08/18              | 221283578758630e8616ecf473495795.xls |
| Tribunal Justiça de Sergipe | 10/18              | 4542a603656cb77c38f26523836b06bd.xls |
| Tribunal Justiça de Sergipe | 09/18              | 54fe54b0142693407d045ba4c06eba0d.xls |
| Tribunal Justiça de Sergipe | 07/18              | a06c167c05c407875b5b3d769b4f5afd.xls |
| Tribunal Justiça de Sergipe | 06/18              | b7f59b15dc9db2d215620c9cf9479700.xls |
| Tribunal Justiça de Sergipe | 03/18              | d41f05004dee30f39a885f54941ea721.xls |
| Tribunal Justiça de Sergipe | 11/18              | e10c0dd8c41603b15495055b9bab797e.xls |
| Tribunal Justiça de Sergipe | 02/18              | ef2e75f982afa2ff0a7270b9a25193d7.xls |
| Tribunal Justiça de Sergipe | 04/18              | f5d19c1151b95a380e2167350742b950.xls |

**Comment by danielfireman** [comment]
Poderia colocar um print ou descrever um ou dois exemplos de como essas planilhas são versus o que é esperado? Dessa forma talvez possa ajudar.

**Comment by viniagostini** [comment]
Claro!

Planilhas que seguem o modelo:
![image](https://user-images.githubusercontent.com/12215291/54823802-b0156980-4c87-11e9-90e8-88f1b1139fe1.png)

Esse caso em particular:
![image](https://user-images.githubusercontent.com/12215291/54823637-39786c00-4c87-11e9-88f9-6eaaaf525495.png)

**Comment by viniagostini** [comment]
A única estratégia que pensei até agora é encontrar o tamanho do header pra diferenciar esses dois casos. Minha única preocupação é que esses textos que ficam ao lado do header possam interferir, mas ainda assim, posso manter uma contagem até encontrar uma célula vazia.

Vou implementar isso e rodar uns testes com todas as planilhas pra ver se alguma tem algum texto em uma célula colada com o header. Se não, sucesso!

@danielfireman o que acha?

**Comment by danielfireman** [comment]
Entendo. Pensei numa coisa aqui. Será que não da pra montar um mapa on the fly com os headers e número das colunas nessas planilhas? A partir da daí varrer os headers que conhecemos e estão no modelo fazendo buscas nesse mapa.

Imagino que tenha um conjunto mínimo de headers para a gente decretar sucesso e creio que serão esses das planilhas menores.

**Comment by viniagostini** [comment]
Tu diz usar o texto do header como chave no mapa? Ou escolher preencher no mapa o elemento da chave que mais se aproxima com o texto que está no header?

Se for uma dessas coisas que eu entendi, me parece um pouco mais complicado de implementar e testar, mas é uma abordagem que generaliza bem mais o problema e isso pode ser ótimo pra gente se essas planilhas começarem a mudar.

**Comment by danielfireman** [comment]
> Tu diz usar o texto do header como chave no mapa? Ou escolher preencher no mapa o elemento da chave que mais se aproxima com o texto que está no header?

Mais ou menos. Na primeira versão, não quis dizer "mais se aproxima" e sim um match exato ou um startsWith. Por exemplo:

Na planilha:
```
para cada header:
   mapa[header.lower().trim()] = index
```

Depos (lembrando que h já foi lower e trimmed também):
```
para cada elemento m do modelo:
   para cada elemento h do mapa:
      if h.startsWitn(m):
         considerar index
```

Ficou mais claro?

**Comment by viniagostini** [comment]
Ficou sim!

Essa abordagem seria muito boa se a planilha nos ajudasse. 
Você reparou que as colunas ``cpf`` e ``nome`` são mescladas com a linha de cima? Olha o que acontece com o array que representa o header dessa aba.

``` javascript
[ undefined, undefined, 'Abono de permanência', 'Outra - Detalhe', 'Outra - (R$)', 'Total de Direitos Pessoais', undefined, 'OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna "OUTRA" e a discriminação da vantagem na coluna "Detalhe"' ]
```
Nós não íamos conseguir casar o `nome` e o `cpf` do modelo com o header porque eles ficam como undefined. Além disso, nesse caso em particular, `Outra` casaria duas vezes com o nosso modelo, aí teria que tratar isso também.

Esses problemas a gente ainda pode contornar. Eu vou verificar se o texto do header tem alguma variação nas planilhas, se isso acontecer, aí sim acho que nossa vida vai ficar bem mais difícil.

**Comment by danielfireman** [comment]
Sobre o nome e o CPF, tem alguma planilha que eles não são os dois primeiros? Estou com a impressão que nesse caso podemos fixar, mas checa por favor.

Também removeria a string "(R$)" de todos os headers e removeria espaços (além de colocar tudo para minúsculo). Consegue rapidinho fazer esse teste e postar os resultados lado a lado com o modelo? Ou é algo complicado de fazer?

**Comment by viniagostini** [comment]
Dá pra fazer rapidex

**Comment by danielfireman** [comment]
Massa! Estarei no aguardo :D

**Comment by viniagostini** [comment]
Demorou um pouco pra rodar :sweat_smile: 

Esses são os resultados "crus":
```javascript
[ '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total Vantagens Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de Permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total Vantagens Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra 1 DIR.PES. (R$)","Detalhe","Outra 2 DIR.PES. (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais"]',
  '[null,null,"Abono de permanência (R$)","Vantagens Art. 184, I, e 192, I, Lei 1.711/52 (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais","OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total Direitos Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência", "Outra - Detalhe","Outra - (R$)","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Vant. Art. 192, I\\nda Lei 8.112/90","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Abono de Permanência-GNAT (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$) ","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total Vantagens Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\"","cpfsrv","nmesrv","SomaDeSomaDeSomaDevalrub"]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)  ","Detalhe   \\"Vant.Pessoal\\"","Outra (R$)","Detalhe","Total Vantagens Pessoais",null,"OBSERVAÇÃO: Se houver alguma VANTAGEM PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Abono de Permanência-GNAT (R$)","Outra (R$)","Detalhe","Total de Direitos Pessoais",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]',
  '[null,null,"Abono de permanência (R$)","Outra (R$)","Detalhe","Outra (R$)","Detalhe"," ",null,"OBSERVAÇÃO: Se houver algum DIREITO PESSOAL que for diferente de Abono de Permanência, o valor deverá ser informado na coluna \\"OUTRA\\" e a discriminação da vantagem na coluna \\"Detalhe\\""]' ]
```

Vou limpar um pouco isso aqui e formatar melhor

**Comment by danielfireman** [comment]
Você fez as considerações do CPF e Nome que eu pedi? Também executa as limpezas, acho que são importantes para ter uma visão mais legal.

Outra limpeza fácil de fazer é tirar tudo que vier depois do "-"

**Comment by viniagostini** [comment]
Todos os headers começam com CPF e Nome sim, eu tive que verificar isso pra implementar a função que acha a posição do header na planilha.

**Comment by viniagostini** [comment]
Pronto! Lembrei de um truquezinho do console do navegado pra adiantar meu lado :smile: 

Essas são todas as possibilidades de headers que existem nas planilhas:
![image](https://user-images.githubusercontent.com/12215291/54832852-c0cfda80-4c9b-11e9-8498-fcb6a03db5f9.png)

Se tu clicar na imagem dá pra ver com uma resolução aceitável

**Comment by danielfireman** [comment]
Ponto,  acho que vai rolar sim. Poderia fazer as limpezas que pedi e gerar
a tabela novamente, por favor?

Em sex, 22 de mar de 2019 13:14, Vinicius Alencar Agostini <
notifications@github.com> escreveu:

**Comment by viniagostini** [comment]
Feito! 
![image](https://user-images.githubusercontent.com/12215291/54835325-a3513f80-4ca0-11e9-8eb3-5df1814bc930.png)

Eu acho que tentar casar com o modelo não vai dar certo por conta dos seguintes casos:

1.  Linha 6; Coluna 3
2.  Linha 12; Coluna 3;
3.  Linha 14; Coluna 3;
e etc.

Uma coisa que eu reparei é que a informação que varia é a que está entre as colunas `Abonodepermanência` e `TotalDireitosPessoais` e em todos os casos, `Outra` e `Detalhe` vão se alternando. O que daria pra fazer é gerar um modelo que case com isso a partir do espaço entre `Abonodepermanência` e `TotalDireitosPessoais`.

O que acha?
