### ISSUE TITLE
Códigos de erros

### ISSUE THREAD

**Issue by viniagostini** [dadosjusbr/parser#21]
Definir códigos para os diferentes tipos de erros que possam ocorrer na aplicação, para que os serviços que requisitam o parsing possam saber o que aconteceu caso um erro seja retornado.
Ex:
{
PASSWORD_PROTECTED_FILE_ERROR: 1,
SHEET_NOT_FOUND: 2
}
E assim por diante.

**Comment by danielfireman** [comment]
Hoje em dia, a API vai retornar um texto? 

Eu não vejo isso como uma melhoria. Isso me soa como parte fundamental do design da API.

**Comment by viniagostini** [comment]
Hoje em dia é um JSON representando o objeto da exceção lançada. 

Massa, faz sentido, vou tirar o label.
