### ISSUE TITLE
Coluna indevida impede que o cálculo do tamanho do header seja realizado na aba Indenizações

### ISSUE THREAD

**Issue by viniagostini** [dadosjusbr/parser#27]
![image](https://user-images.githubusercontent.com/12215291/56857662-c679a980-6946-11e9-8bdd-88592f9a5bb9.png)

Esse é um caso extremamente particular e ocorre apenas em uma planilha, mas achei um bom exemplo para nos lembrar que é necessário uma heurística pra detectar quando há algum problema relacionado ao header e lançar um erro pra que tratemos esse caso manualmente.

Essa coluna tem o título vazio e cada campo aponta pra outro arquivo, o que não faz sentido nenhum se o mesmo não for publicado junto.

| Tribunal                                    | Mês/ano referência | arquivo                              |
|---------------------------------------------|--------------------|--------------------------------------|
| Tribunal de Justiça do Distrito Federal e Territórios | 04/18 | b7f9bbbf4d306086d1cfad83d30863d4.xls |

**Comment by danielfireman** [comment]
Qual foi a solução adotada para esse caso?

**Comment by viniagostini** [comment]
Ainda nenhuma :)

O que eu pensei é em usar o tamanho do header encontrado para identificar se o mesmo foi encontrado com sucesso. 

Por exemplo:  
Esse é o header que geralmente encontramos na aba indenizações:
![image](https://user-images.githubusercontent.com/12215291/56868424-9ffc5280-69c8-11e9-95e7-1f787a3196d6.png)

Sabemos que se o header não possuir essas colunas: `CPF, nome, aux. alimentação, aux. pré escolar, aux. saúde, aux. moradia, ajuda de custo e total indenizações` tem algo de errado.

Assim, podemos verificar se ```header.length >= 8``` caso não seja, lançamos um erro.

**Comment by danielfireman** [comment]
Sim, ta bacana. Depois mapeamos as colunas com os conteúdos e realizamos o processamento.
