### ISSUE TITLE
Existem planilhas sem a aba "Dados Cadastrais"

### ISSUE THREAD

**Issue by viniagostini** [dadosjusbr/parser#32]
Como tratamos isso? Deixamos em branco as informações contidas nessa aba para esses casos? Lançamos um erro e notificamos (manualmente) o CNJ que a aba está faltando?

O que tu acha @danielfireman?

**Comment by viniagostini** [comment]
Para referência futura, essas planilhas não contém a aba Dados Cadastrais:

dd78cb203e15af1ee093d974cb350d8a.xls
bdb6749ff5e1eef3368e3e14e78592ca.xls
b9c27130e99e861a90fd98bddac8976f.xls
9837cea079edf427ce8aae2b9f351e07.xls
8870549307918b3a9038696bddd8cb47.xls
29ad327d7b11d089acad776ca975ae00.xls

**Comment by danielfireman** [comment]
Acho que temos que nos comunicar com a CNJ. 

Estas planilhas são de que mês?
