### ISSUE TITLE
Adicionar logs

### ISSUE THREAD

**Issue by viniagostini** [dadosjusbr/parser#39]
Para cada request logar coisas como httpStatus, informações da requisição, tempo de resposta e etc.

Seria bacana fazer um esquema de log para cada etapa do parsing também.

**Comment by danielfireman** [comment]
Olhar [ubber-zap](https://github.com/uber-go/zap/blob/master/README.md) e logrus. Podem ajudar bastante.

**Comment by viniagostini** [comment]
@danielfireman essa issue aqui é do Parser, mas olhando essas que tu mandou consegui achar coisas similares pra Node :)
